BEGIN_CLS(ecl::Scenery)
P_RO(Flags)
P_RO(LevelName)
P_RO(GUID)
P(CoverAmount)
// P_REF(Physics)
P_REF(Sound)
P_REF(Fade)
P_REF(Template)
P(VisualResourceID)
P(DefaultState)
P(RenderChannel)
P(IsBlocker)
P(RenderFlags)
P_BITMASK(RenderFlags)
END_CLS()


BEGIN_CLS(ecl::Scenery::SoundSettings)
P_REF(Template)
P(SoundAttenuation)
P(SoundInitEvent)
P(LoopSound)
END_CLS()


BEGIN_CLS(ecl::Scenery::FadeSettings)
P_REF(Template)
P(FadeIn)
P(Opacity)
P(FadeGroup)
END_CLS()
